name: Assign to Issue Based on Label
description: Automatically assign users to issues based on labels
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  assignment:
    description: Comma-separated list of "<label> | <username>" pairs to assign users to issues based on labels
    required: true

runs:
  using: node20
  main: dist/index.js

branding:
  icon: tag
  color: green
