name: Test GitHub Action

on:
  issues:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignment: philipp | Planeshifter, athan | kgryte